CREATE DATABASE MyFood;

CREATE TABLE DBO.CAD_USUARIO(
	ID BIGINT PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CPF VARCHAR(14) NOT NULL
)
GO
CREATE TABLE DBO.CAD_EMPRESA(
	ID BIGINT PRIMARY KEY IDENTITY,
	RAZAO_SOCIAL VARCHAR(100) NOT NULL,
	NOME_FANTASIA VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(18) NOT NULL
)
GO
CREATE TABLE DBO.CAD_PRODUTO(
	ID BIGINT PRIMARY KEY IDENTITY,
	EMPRESA_ID BIGINT FOREIGN KEY REFERENCES DBO.CAD_EMPRESA(ID) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
	PRECO DECIMAL NOT NULL
)
GO
CREATE TABLE DBO.OPR_PEDIDO(
	ID BIGINT PRIMARY KEY IDENTITY,
	USUARIO_ID BIGINT FOREIGN KEY REFERENCES DBO.CAD_USUARIO(ID) NOT NULL,
	VALOR_TOTAL DECIMAL NOT NULL,
	FORMA_PAGAMENTO VARCHAR(2) NOT NULL,
	PAGO VARCHAR(1) NOT NULL,
	FINALIZADO VARCHAR(1) NOT NULL
)
GO
CREATE TABLE DBO.OPR_PEDIDO_PRODUTO(
	ID BIGINT PRIMARY KEY IDENTITY,
	PEDIDO_ID BIGINT FOREIGN KEY REFERENCES DBO.OPR_PEDIDO(ID) NOT NULL,
	PRODUTO_ID BIGINT FOREIGN KEY REFERENCES DBO.CAD_PRODUTO(ID) NOT NULL,
	QUANTIDADE BIGINT NOT NULL
)
GO
ALTER TABLE DBO.OPR_PEDIDO_PRODUTO
ADD CONSTRAINT OPR_PEDIDO_PRODUTO_UK UNIQUE (PEDIDO_ID, PRODUTO_ID);