--STRUCTURE
CREATE DATABASE MyFood;

CREATE TABLE DBO.CAD_USUARIO(
	ID BIGINT PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CPF VARCHAR(14) NOT NULL
)
GO
CREATE TABLE DBO.CAD_EMPRESA(
	ID BIGINT PRIMARY KEY IDENTITY,
	RAZAO_SOCIAL VARCHAR(100) NOT NULL,
	NOME_FANTASIA VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(18) NOT NULL
)
GO
CREATE TABLE DBO.CAD_PRODUTO(
	ID BIGINT PRIMARY KEY IDENTITY,
	EMPRESA_ID BIGINT FOREIGN KEY REFERENCES DBO.CAD_EMPRESA(ID) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
	PRECO DECIMAL NOT NULL
)
GO
CREATE TABLE DBO.OPR_PEDIDO(
	ID BIGINT PRIMARY KEY IDENTITY,
	USUARIO_ID BIGINT FOREIGN KEY REFERENCES DBO.CAD_USUARIO(ID) NOT NULL,
	VALOR_TOTAL DECIMAL NOT NULL,
	FORMA_PAGAMENTO VARCHAR(2) NOT NULL,
	PAGO VARCHAR(1) NOT NULL,
	FINALIZADO VARCHAR(1) NOT NULL
)
GO
CREATE TABLE DBO.OPR_PEDIDO_PRODUTO(
	ID BIGINT PRIMARY KEY IDENTITY,
	PEDIDO_ID BIGINT FOREIGN KEY REFERENCES DBO.OPR_PEDIDO(ID) NOT NULL,
	PRODUTO_ID BIGINT FOREIGN KEY REFERENCES DBO.CAD_PRODUTO(ID) NOT NULL,
	QUANTIDADE BIGINT NOT NULL
)
GO
ALTER TABLE DBO.OPR_PEDIDO_PRODUTO
ADD CONSTRAINT OPR_PEDIDO_PRODUTO_UK UNIQUE (PEDIDO_ID, PRODUTO_ID);
GO

-- DATA

-- USUARIO
INSERT INTO DBO.CAD_USUARIO VALUES ('Nathan Valentim', 'nathan.valentim98@gmail.com', '458.374.668-78')
GO
INSERT INTO DBO.CAD_USUARIO VALUES ('Gabriela Araujo', 'gabi.arj@hotmail.com', '464.694.288-78')
GO

-- EMPRESA
INSERT INTO DBO.CAD_EMPRESA VALUES ('ARCOS DOURADOS COMERCIO DE ALIMENTO', 'MCDONALD''S', '42.591.651/0001-43')
GO
INSERT INTO DBO.CAD_EMPRESA VALUES ('BK BRASIL OPERAÇÃO E ASSESSORIA A RESTAURANTE S.A', 'BURGER KING', '13.574.594/0001-96')
GO
INSERT INTO DBO.CAD_EMPRESA VALUES ('CFK COMÉRCIO DE ALIMENTOS LTDA', 'KFC', '08.281.783/0001-30')
GO

-- PRODUTO
INSERT INTO DBO.CAD_PRODUTO VALUES (
	(SELECT ID FROM DBO.CAD_EMPRESA WHERE NOME_FANTASIA = 'MCDONALD''S'),
	'Big MC',
	'Dois burgers, alface queijo e molho especial',
	22
)
GO
INSERT INTO DBO.CAD_PRODUTO VALUES (
	(SELECT ID FROM DBO.CAD_EMPRESA WHERE NOME_FANTASIA = 'MCDONALD''S'),
	'Quarteirão',
	'Pão, queijo, carne, queijo e pão',
	24
)
GO
INSERT INTO DBO.CAD_PRODUTO VALUES (
	(SELECT ID FROM DBO.CAD_EMPRESA WHERE NOME_FANTASIA = 'MCDONALD''S'),
	'Triplo bacon',
	'Três burgers, queijo e bacon',
	21
)
GO
INSERT INTO DBO.CAD_PRODUTO VALUES (
	(SELECT ID FROM DBO.CAD_EMPRESA WHERE NOME_FANTASIA = 'BURGER KING'),
	'Staker triplo',
	'Três carnes gigantes',
	31
)
GO
INSERT INTO DBO.CAD_PRODUTO VALUES (
	(SELECT ID FROM DBO.CAD_EMPRESA WHERE NOME_FANTASIA = 'BURGER KING'),
	'Whoper duplo',
	'Duas carnes, molho e salada',
	27
)
GO
INSERT INTO DBO.CAD_PRODUTO VALUES (
	(SELECT ID FROM DBO.CAD_EMPRESA WHERE NOME_FANTASIA = 'BURGER KING'),
	'Staker triplo',
	'Três carnes gigantes',
	31
)
GO
INSERT INTO DBO.CAD_PRODUTO VALUES (
	(SELECT ID FROM DBO.CAD_EMPRESA WHERE NOME_FANTASIA = 'KFC'),
	'Balde de frango frito',
	'Balde com pedaços de frango frito',
	45
)
GO
INSERT INTO DBO.CAD_PRODUTO VALUES (
	(SELECT ID FROM DBO.CAD_EMPRESA WHERE NOME_FANTASIA = 'KFC'),
	'Molho especial',
	'Molho especial da casa',
	10
)
GO
INSERT INTO DBO.CAD_PRODUTO VALUES (
	(SELECT ID FROM DBO.CAD_EMPRESA WHERE NOME_FANTASIA = 'KFC'),
	'Coca Cola',
	'Refrigerante',
	5
)
GO
INSERT INTO DBO.CAD_PRODUTO VALUES (
	(SELECT ID FROM DBO.CAD_EMPRESA WHERE NOME_FANTASIA = 'KFC'),
	'Pepsi',
	'Refrigerante',
	5
)
GO

  
